### ISSUE TITLE
The specification for `real/sorting_doubles` is incorrect.

### ISSUE THREAD

**Issue by delcypher** [danielschemmel/fp-benchmarks-aachen#10]
The spec for this benchmark claims it is correct w.r.t to all verification tasks. This is not correct.

Our tool reports that an assertion can fail.

```
real/sorting/main.c:10: ASSERTION FAIL: arr[i] >= arr[i - 1]
```

I've checked the generated test case. Which gives these concrete values

```
ktest file : 'test000018.ktest'
args       : ['/tmp/sorting_doubles.x86_64.bc']
num objects: 2
object    0: name: b'a'
object    0: size: 8
object    0: data: -inf
object    1: name: b'b'
object    1: size: 8
object    1: data: inf
```

I've taken the ktest file and replayed it on the native binary and confirmed. The problem here I think is that when `a` is `-inf` and `b` is `inf` then you will have an element `a + b` in the array being sorted which evaluates to NaN

https://github.com/danielschemmel/fp-benchmarks-aachen/blob/4f8338ada2066ba38fa5b59cfda8ec6ed917f2bd/real/sorting/main.c#L20

after doing a sort the NaN will still be in the array and will not be comparable to any other element.

**Comment by danielschemmel** [comment]
You are of course completely right. I will need to check why this did not come up in our internal testing!

The issue itself is addressed with another assume call in 85ea9c7.

**Comment by delcypher** [comment]
@danielschemmel Thanks for confirming and fixing. You might want to keep this issue open though until you figure out why your testing didn't find this issue.

**Comment by danielschemmel** [comment]
IIRC we had a problem with this test, but did not further investigate at that point due to other outstanding issues, after which it probably just got buried.

**Comment by danielschemmel** [comment]
I have verified that we had a problem with this test as well, which got buried when we refocused on adding support for vectorization.
