### ISSUE TITLE
`ld-unnormal_default.x86_64` is mis-compiled by Clang when optimizations are enabled

### ISSUE THREAD

**Issue by delcypher** [danielschemmel/fp-benchmarks-aachen#14]
When `ld-unnormal_default.x86_64` is built with optimizations enabled the benchmark is aggressively constant folded so many of the checks are not performed at run time. A bug in [LLVM](https://llvm.org/bugs/show_bug.cgi?id=31294) means this constant folding is done incorrectly which results in the benchmark always failing an assert when compiled with Clang and optimizations enabled.

The solution for now is to always build this benchmark without optimizations. The bug in LLVM will not be simple to fix so this will do for now.

I'll be submitting a fix soon.

**Comment by danielschemmel** [comment]
We can verify that this behavior happens for us, and that your proposed fix does indeed solve it.
