### ISSUE TITLE
syn/atof_default.x86_64 is incorrect despite the spec saying it should be correct

### ISSUE THREAD

**Issue by delcypher** [danielschemmel/fp-benchmarks-aachen#18]
Our tool just found a bug in this benchmark

```
Error: ASSERTION FAIL: out < 1
File: /home/user/fp-bench/benchmarks/c/aachen/syn/atof/test.c
Line: 14
assembly.ll line: 87
```

The generated test for this makes the "input" be

```
object    0: name: b'input'
object    0: size: 8
object    0:
object   0[0]: 0x00
object   0[1]: 0x00
object   0[2]: 0x32
object   0[3]: 0x65
object   0[4]: 0x31
object   0[5]: 0x00
object   0[6]: 0x00
object   0[7]: 0x00
```

effectively this means we pass the following C string to `atof()` during execution

```
"0.2e1"
```

This is `2.0` which means `assert(out < 1)` fails. This is a genuine bug which I have reproduced natively.

We never found this bug before because we previously had never let our tool execute for so long (~ 1hour).

**Comment by danielschemmel** [comment]
Yes, it seems we missed that `atof` also supports scientific notation.

**Comment by danielschemmel** [comment]
Commit 28399e5c23b5fabbbdd579e861f95a537651a67d should ensure that scientific notation allows for large numbers by testing for `[eE]` beforehand (the `[pP]` suffix is not legal for decimal literals if I am not mistaken).
