### ISSUE TITLE
sqr_ family of benchmarks incorrect

### ISSUE THREAD

**Issue by delcypher** [danielschemmel/fp-benchmarks-aachen#22]
Aachen's fork of KLEE detected a problem with the `aachen/syn/sqr_float-flow.x86_64` benchmark. This problem suggests that there is very likely to be a problem with *all* the variants of this benchmark. The assertion that fails is

```
assert(b == INFINITY || b == 0 || (a * 0.99 <= b && a >= b * 0.99) && "this should pass...");
```

Sidenote: Because the variables here are `float` the constants should be `0.99f`. However the bug is still present even if this minor problem is removed.

Our (Imperial's) version of KLEE did not detect an error here due to the way we set up our solver timeout.

The problematic value generated for `f` is `-0x1.8100f8p-75` (C99 hex float format). This is approximately `-3.9808458254123446e-23`.

Native replay of the generated KTest file confirms that the bug is reproducible.

The `a *0.99 <= b` condition is false for the value of `f` in the generated test case.

This assertion appears in the noflow (it's expected to fail here though) and long double and double variants too so I would expect those variants to fail too.

**Comment by danielschemmel** [comment]
While this is annoying, it is also kind of cool. What happens is that the test attempts to show that squaring and then taking the square root of a number results in either infinity (on overflow), zero (on underflow) or roughly the same number as before.

What I missed when writing the test is that the approximation can be quite significant, when _not quite_ underflowing! The example input you mention results in the smallest denormal number after squaring, thus losing 22 bits of precision. This causes the final result to not be an over-/underflow situation, but still miss the expected range for the result.

I really like this result, as it perfectly shows the pitfalls of floating point numbers and how our tools can find even pretty damn exotic failures - we should probably discuss this in the paper!

**Comment by delcypher** [comment]
@danielschemmel Just to note we don't necessarily need to fix this benchmark during our runs. Originally your tool was penalised due to it not matching the spec but now that we incorporate information from attempting to replay all bug reporting KTest files your false positive gets turned into a true positive during ranking.

We should definitely fix the benchmark at some point though.
