### ISSUE TITLE
klee_assume(f == f) is not a good way to ignore paths where symbolics are NaN

### ISSUE THREAD

**Issue by delcypher** [danielschemmel/fp-benchmarks-aachen#7]
I've noticed that the `syn/halve/test.c` benchmark does this

```c
float f = 131, g;
#if defined(USE_KLEE)
klee_make_symbolic(&f, sizeof(f), "f");
#endif
klee_assume(f == f);
```

I presume that the use of `klee_assume(f == f)` is avoid considering paths where `f` is a nan. Although this will probably work I don't think this is a good idea for two reasons

* It is not very clear what is being done here. `klee_assume(isnan(f))` is much clearer.
* Very aggressive compilers might optimize this to `klee_assume(true)`. I've not seen this happen but [apparently is can](http://stackoverflow.com/questions/570669/checking-if-a-double-or-float-is-nan-in-c) under `-ffast-math`. Although this is not a scenario we are checking I see no reason to avoid using the `isnan()` here.

**Comment by danielschemmel** [comment]
Compilers _may not_ optimize this scenario, as the result of `f == f` is not known at compile time (passing a pointer to the object that `f` refers to to an unknown function -- `klee_make_symbolic` -- changes the status of that value from "undefined" to "unknown", as the definition of `klee_make_symbolic` cannot be known to the compiler).

The case you are referring to, explicitly allows the compiler to ignore floating point rules to generate faster code. Allowing the compiler to make invalid assumptions, has the obvious drawback, that the compiler may generate invalid assumptions ;)

**Comment by delcypher** [comment]
@danielschemmel Sure what you mention above is all true but why not just use `isnan()`? It's a lot clearer and would do the right thing even if `-ffast-math` is being used.

**Comment by danielschemmel** [comment]
@delcypher There are a few reasons against using `isnan`:
- `isnan` is guaranteed to be a macro, one legal implementation of which is self comparison
- its implementation may actually be problematic for `klee_assume`
- We want to discourage simply recognizing the usage of a function, and instead promote relying on floating point semantics (in our tools at least)

I am aware that this is not a problem for either uclibc nor glibc, which use basically the same implementation that uses a type generic macro falling down to a builtin, and your argument for clarity does have its own merit. Personally, however I prefer a solution that is known to be correct w.r.t. any valid C compiler and library.

**Comment by danielschemmel** [comment]
Having discussed this in the conference call, our decision was to assume `-ffast-math` is disabled and floating point behavior is correct.
